version: "3.2"
services:
  satellite:
    container_name: vgs-satellite
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8089:8089
      - 9098:9098
      - 9099:9099
    volumes:
      - ~/.vgs-satellite:/data
  test:
    container_name: vgs-satellite-tests
    build:
      context: .
      dockerfile: Dockerfile.test
