version: '3'
services:
  mitmproxy:
    image: "mitmproxy/mitmproxy:5.0.1"
    env_file:
      - ".env"
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
      - "${WEB_PORT}:${WEB_PORT}"
    command: "mitmweb --listen-port ${PROXY_PORT} --web-port ${WEB_PORT} --web-iface 0.0.0.0 ${MITM_ARGS} -s /tmp/mitm-requests-json.py"
    volumes:
      - "./script/mitm-requests-json.py:/tmp/mitm-requests-json.py"
      - "./mitm-requests:${MITM_DIR}"
      - "./.cache:/src/.cache"

  satellite:
    build:
      context: .
    env_file:
      - ".env"
    ports:
      - "${SATELLITE_PORT}:${SATELLITE_PORT}"
    volumes:
      - "./mitm-requests:${MITM_DIR}"