version: 2
jobs:
  build:
    docker:
      - image: cypress/browsers:node12.16.1-chrome80-ff73
        environment:
          ## this enables colors in the output
          TERM: xterm
          NODE_OPTIONS: --max-old-space-size=2048
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --unsafe-perm
      - run: npm test
      - store_artifacts:
          path: /root/app/client/cypress/screenshots/
  build_python:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run linter for Python sources
          command: flake8 satellite
      - run:
          name: Run Python unit tests
          command: pytest satellite/tests
  smoketest:
    docker:
      - image: cypress/browsers:node12.16.1-chrome80-ff73
        environment:
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --unsafe-perm
      - run:
          name: Test YAML Consistency
          command: npm run smoketest
      - store_artifacts:
          path: /root/app/client/cypress/screenshots/


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build_python
  periodical_smoke_test:
    ## create dashboard route by uploading satellite-generated YAML
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - smoketest
